#version: "3"

services:
  app:
    build: ./app/
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - db
    links:
      - db

  web-proxy:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - db

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
      RABBITMQ_HOST: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/mount:/var/lib/rabbitmq
    env_file:
      - ./rabbitmq/.env

    restart: on-failure

  db:
    image: postgres:16-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=sa


  worker:
    build: ./app/
    image: worker
    environment:
      RABBITMQ_USER: rmuser
      RABBITMQ_PASSWORD: rmpassword
      RABBITMQ_HOST: rabbitmq
    restart: always
    volumes:
      - ./app:/app
    working_dir: /app
    env_file:
      - ./app/.env


    command: python -u worker.py
    depends_on:
      - rabbitmq

  webui:
    build: ./webview/
    image: webview
    environment:
      RABBITMQ_USER: rmuser
      RABBITMQ_PASSWORD: rmpassword
      RABBITMQ_HOST: rabbitmq
    volumes:
      - ./webview:/webview
    ports:
      - 8501:8501
    working_dir: /webview
    env_file:
      - ./webview/.env

    depends_on:
      - app
